version: '3.8'
services:
  mysql:
    image: mysql:8.0.33
    container_name: sql_demo
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sample
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    ports:
      - 3316:3306
